absolut_config:
  path: './Absolut' # Put path to Absolut (/ABS/PATH/TO/Absolut/)
  process: 0
  startTask: 5
antigens:
- 4ZFO_F
- 1ADQ_A
- 5EZO_A
- 4OII_A
- 4OKV_E
- 1NCA_N
- 5CZV_A
- 5JW4_A
random_seeds:
- 0
- 1
- 2
rs_num_iter: 200
rs_batch_size: 1
save_dir: './results/RS/'  # Put path where you want results to be stored '/ABS/PATH/TO/results/'
sequence_length: 11
