absolut_config:
  path: './Absolut' # Put path to Absolut (/ABS/PATH/TO/Absolut/)
  process: 20
  startTask: 30
antigens:
- 1ADQ_A
- 1FBI_X
- 1H0D_C
- 1NSN_S
- 1OB1_C
- 1WEJ_F
- 2YPV_A
- 3RAJ_A
- 3VRL_C
- 2DD8_S
- 1S78_B
- 2JEL_P
random_seeds:
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
- 50
- 51
rs_num_iter: 200
rs_batch_size: 1
save_path: './results/RS/'  # Put path where you want results to be stored '/ABS/PATH/TO/results/'
sequence_length: 11
