AbsolutPath: /ABS/PATH/TO/Absolut
antigens:
- 4ZFO_F
- 1ADQ_A
- 5EZO_A
- 4OII_A
- 4OKV_E
- 1NCA_N
- 5CZV_A
- 5JW4_A
methods
  BO_global_transformed_overlap:
    kernel: transformed_overlap
  BO_glocal_transformed_overlap:
    kernel: transformed_overlap
  BO_blocal_transformed_overlap:
    kernel: transformed_overlap
  BO_transformed_overlap:
    kernel: transformed_overlap
  BO_ssk:
    kernel: ssk
  BO_hebo:
    kernel: ssk
  GA:
    kernel: GA
  RS:
    kernel: RS
  RealData:
    kernel: RealData
random_seeds:
- 0
- 1
results_dir: './results/'  # Put path where you fetch the results '/ABS/PATH/TO/results/'
save_dir: './CDRH3_binding_visualisation/'  # Put path where visualisations should be saved /ABS/PATH/TO/CDRH3_binding_visualisation
sequence_length: 11
visualisation_timesteps:
- 200

