name: DGM
channels:
  - dglteam
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _py-xgboost-mutex=2.0=cpu_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - botorch=0.5.0=0
  - bottleneck=1.3.2=py39hdd57654_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py39hf3d152e_0
  - cffi=1.14.6=py39h400218f_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=3.4.7=py39hd23ed53_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.10.0=py39h06a4308_0
  - cython=0.29.24=py39he80948d_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - dgl=0.7.1=py39_0
  - einops=0.3.2=pyhd8ed1ab_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py39hf3d152e_3
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gpytorch=1.5.0=pyhd8ed1ab_1
  - grakel=0.1.8=py39h5472131_2
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - gym
  - icu=58.2=he6710b0_3
  - idna=3.2=pyhd3eb1b0_0
  - ipython=7.26.0=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py39h06a4308_1
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.14=h7b6447c_0
  - libxgboost=1.4.2=h9c3ff4c_0
  - libxml2=2.9.12=h03d6c58_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.4.2=py39h06a4308_0
  - matplotlib-base=3.4.2=py39hab158f2_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.3.0=h726a3e6_557
  - mkl-service=2.4.0=py39h3811e60_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39hde0f152_0
  - munkres=1.1.4=py_0
  - ncurses=6.2=h58526e2_4
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.2=pyhd3eb1b0_0
  - ninja=1.10.2=h4bd325d_0
  - nose=1.3.7=py_1006
  - numexpr=2.7.3=py39h22e1b3c_1
  - numpy=1.20.3=py39hf144106_0
  - numpy-base=1.20.3=py39h74d4b33_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - pandas=1.3.2=py39h8c16a72_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py39h2c7a002_0
  - pip=21.2.4=pyhd8ed1ab_0
  - psutil
  - prompt-toolkit=3.0.17=pyhca03da5_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-xgboost=1.4.2=py39hf3d152e_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.7=h49503c6_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=py3.9_cuda11.1_cudnn8.0.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py39h27cfd23_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h46c0cb4_0
  - requests=2.26.0=pyhd3eb1b0_0
  - scikit-learn=0.24.2=py39ha9443f7_0
  - scipy=1.7.1=py39h292c36d_2
  - setuptools=58.0.4=py39hf3d152e_0
  - simanneal
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_1
  - tbb=2021.3.0=h4bd325d_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h27826a3_1
  - torchaudio=0.9.0=py39
  - torchvision=0.10.0=py39_cu111
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.62.1=pyhd3eb1b0_1
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzdata=2021a=he74cb21_1
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xgboost=1.4.2=py39hf3d152e_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - autograd==1.3
    - biopython==1.79
    - click==8.0.3
    - cma==2.7.0
    - filelock==3.4.0
    - func-timeout==4.3.5
    - geneticalgorithm==1.0.2
    - huggingface-hub==0.2.1
    - packaging==21.3
    - pymoo==0.5.0
    - regex==2021.11.10
    - sacremoses==0.0.46
    - terminalplot==0.3.0
    - tokenizers==0.10.3
    - transformers==4.13.0
prefix: /home/alexc/anaconda3/envs/DGM
